name: check frontend

on:
    push:
      branches: ["main"]
      paths:
        - "frontend/**"
        - ".github/workflows/check-frontend.yml"
    pull_request:
      branches: ["main"]
      paths:
        - "frontend/**"
        - ".github/workflows/check-frontend.yml"

jobs:
    format:
      runs-on: ubuntu-24.04
      defaults:
        run:
          working-directory: ./frontend
      steps:
        - name: Checkout your repository using git
          uses: actions/checkout@v4
        - name: Copy .mise.toml
          run: cp .mise.toml ../.mise.toml
        - name: Setup mise
          uses: jdx/mise-action@v2
          with:
            install: true
            cache: true
        - name: Install dependencies
          run: bun install --frozen-lockfile
        - name: Format
          run: bun run format:check

    lint:
      runs-on: ubuntu-24.04
      defaults:
        run:
          working-directory: ./frontend
      steps:
        - name: Checkout your repository using git
          uses: actions/checkout@v4
        - name: Copy .mise.toml
          run: cp .mise.toml ../.mise.toml
        - name: Setup mise
          uses: jdx/mise-action@v2
        - name: Install dependencies
          run: bun install --frozen-lockfile
        - name: Lint
          run: bun run lint
  
    build:
      runs-on: ubuntu-24.04
      defaults:
        run:
          working-directory: ./frontend
      steps:
        - name: Checkout your repository using git
          uses: actions/checkout@v4
        - name: Copy .mise.toml
          run: cp .mise.toml ../.mise.toml
        - name: Setup mise
          uses: jdx/mise-action@v2
          with:
            install: true
            cache: true
        - name: Install dependencies
          run: bun install --frozen-lockfile
        - name: Build
          run: bun run build
