name: check backend
on:
  push:
    branches: ["main"]
    paths:
      - 'backend/**'
      - '.github/workflows/check-backend.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'backend/**'
      - '.github/workflows/check-backend.yml'

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        id: setup-go
        with:
          go-version-file: "backend/go.mod"

      - name: Download Go modules
        shell: bash
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
